# Generated by Django 3.0.8 on 2020-07-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPlayers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('player_1', models.CharField(max_length=200)),
                ('player_2', models.CharField(max_length=200)),
                ('guest_1', models.CharField(blank=True, max_length=200)),
                ('guest_2', models.CharField(blank=True, max_length=200)),
                ('guest_3', models.CharField(blank=True, max_length=200)),
                ('guest_4', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
