# Generated by Django 3.0.8 on 2020-07-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updateform', '0002_logplayers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LogPlayers',
            new_name='LogPlayer',
        ),
    ]
