# Generated by Django 3.0.8 on 2020-07-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateform', '0003_auto_20200729_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logplayer',
            name='player_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logplayer',
            name='player_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
