# Generated by Django 3.0.8 on 2020-07-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0002_hometest_ideabookings_ideaplayers_secondlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest1', models.CharField(blank=True, max_length=10, null=True)),
                ('guest2', models.CharField(blank=True, max_length=10, null=True)),
                ('guest3', models.CharField(blank=True, max_length=10, null=True)),
                ('guest4', models.CharField(blank=True, max_length=10, null=True)),
                ('guest5', models.CharField(blank=True, max_length=10, null=True)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formsapp.CourtTime')),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formsapp.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='IdeaPlayers',
            new_name='Court',
        ),
        migrations.DeleteModel(
            name='IdeaBookings',
        ),
        migrations.AddField(
            model_name='courttime',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formsapp.Court'),
        ),
        migrations.AddField(
            model_name='courttime',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formsapp.Time'),
        ),
    ]
