# Generated by Django 3.0.8 on 2020-07-27 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0004_auto_20200727_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courttime',
            name='court',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formsapp.Court'),
        ),
        migrations.AlterField(
            model_name='courttime',
            name='time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formsapp.Time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formsapp.CourtTime'),
        ),
    ]
