# Generated by Django 3.0.8 on 2020-07-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0006_auto_20200728_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='guest1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='guest2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='guest3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='guest4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='player1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='log',
            name='player2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
