# Generated by Django 3.0.8 on 2020-07-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formsapp', '0007_auto_20200728_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='guest1',
            new_name='guest_1',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='guest2',
            new_name='guest_2',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='guest3',
            new_name='guest_3',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='guest4',
            new_name='guest_4',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='player1',
            new_name='player_1',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='player2',
            new_name='player_2',
        ),
    ]
