# Generated by Django 3.0.8 on 2020-07-24 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('month_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(max_length=10)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Court')),
                ('court_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Time')),
                ('month_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Month')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Player')),
            ],
        ),
    ]
