# Generated by Django 3.0.8 on 2020-07-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200724_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
