# Generated by Django 3.0.8 on 2020-07-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timebooked',
            old_name='time',
            new_name='name',
        ),
    ]
