# Generated by Django 3.0.8 on 2020-07-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_auto_20200722_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='TennisPlayer',
        ),
        migrations.DeleteModel(
            name='TimeBooked',
        ),
        migrations.AddField(
            model_name='block',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.Player'),
        ),
    ]
