# Generated by Django 3.0.8 on 2020-07-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0004_auto_20200723_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
