# Generated by Django 3.0.8 on 2020-07-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0005_auto_20200723_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='block',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.Time'),
        ),
    ]
